### ISSUE TITLE
Als User möchte ich, dass Wasser sich realistisch verhält, damit sich Seen bilden.

### ISSUE THREAD

**Issue by HagenMarin** [hpi-swa-teaching/ComputationalArt#27]

**Comment by KDPawn** [comment]
AK:
- Wasser geht nach unten oder random nach links oder rechts (wenn Block daneben frei ist)
- Zweites Neighbor-Grid, mit dem man Changes betrachten kann
- Wasser sollte sich am Ende ausgleichen (Ausnahme: Wasser muss dafür nach oben fließen)
