### ISSUE TITLE
Als Kunde möchte in die Simulation bestimte Blöcke einfügen können.

### ISSUE THREAD

**Issue by HagenMarin** [hpi-swa-teaching/ComputationalArt#5]
AK:
-man muss einen Blocktyp auswählen können (muss noch nicht visuell sein, es reicht auch über Tastendrücke)
-man muss den ausgewählten Blocktyp im grid mit der Maus platzieren können, dabei muss der Block noch nicht visuell im Fenster abgebildet werden, aber mindestens in der grid Datenstruktur an der richtigen Stelle vorhanden sein

**Comment by KDPawn** [comment]
Spiel soll pausiert sein, um Blöcke placen zu können
